In [1]:
import os

In [2]:
os.chdir('C:/Users/Srinivasa Rao/Desktop/datasets')

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
data=pd.read_csv('telecom.csv')

In [5]:
data.head(3)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   

      PaymentMethod MonthlyCharges  TotalCharges Churn  
0  Electronic check          29.85         29.85    No  
1      Mailed check          56.95        1889.5    No  
2      Mailed check          53.85        108.15   Yes  

[3 rows x 21 columns]

In [6]:
data.describe()

SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [7]:
data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder=LabelEncoder()
data['Churn']=labelencoder.fit_transform(data['Churn'])
data.head(5)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85     0  
1               Mailed check          56.95        1889.5     0  
2               Mailed check          53.85        108.15     1  
3  Bank transfer (automatic)          42.30       1840.75     0  
4           Electronic check          70.70        151.65     1  

[5 rows x 21 columns]

In [9]:
data['PhoneService']=labelencoder.fit_transform(data['PhoneService'])
data['InternetService']=labelencoder.fit_transform(data['InternetService'])

In [10]:
data.head(3)

customerID  gender  SeniorCitizen Partner Dependents  tenure  PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1             0   
1  5575-GNVDE    Male              0      No         No      34             1   
2  3668-QPYBK    Male              0      No         No       2             1   

      MultipleLines  InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service                0             No  ...               No   
1                No                0            Yes  ...              Yes   
2                No                0            Yes  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   

      PaymentMethod MonthlyCharges  TotalCharges Churn  
0  Electronic check          29.85         29.85     0  
1      Mailed check          56.95        1889.5     0  
2      Mailed check          53.85        108.15     1  

[3 rows x 21 columns]

In [11]:
data.corr()

SeniorCitizen    tenure  PhoneService  InternetService  \
SeniorCitizen         1.000000  0.016567      0.008576        -0.032310   
tenure                0.016567  1.000000      0.008448        -0.030359   
PhoneService          0.008576  0.008448      1.000000         0.387436   
InternetService      -0.032310 -0.030359      0.387436         1.000000   
MonthlyCharges        0.220173  0.247900      0.247398        -0.323260   
Churn                 0.150889 -0.352229      0.011942        -0.047291   

                 MonthlyCharges     Churn  
SeniorCitizen          0.220173  0.150889  
tenure                 0.247900 -0.352229  
PhoneService           0.247398  0.011942  
InternetService       -0.323260 -0.047291  
MonthlyCharges         1.000000  0.193356  
Churn                  0.193356  1.000000

In [13]:
data.shape

(7043, 21)

In [14]:
data.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService          int32
MultipleLines        object
InternetService       int32
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                 int32
dtype: object

In [24]:
X=data[['tenure','PhoneService','InternetService','MonthlyCharges']]
y=data['Churn']

In [16]:
X


tenure  PhoneService  InternetService  MonthlyCharges
0          1             0                0           29.85
1         34             1                0           56.95
2          2             1                0           53.85
3         45             0                0           42.30
4          2             1                1           70.70
5          8             1                1           99.65
6         22             1                1           89.10
7         10             0                0           29.75
8         28             1                1          104.80
9         62             1                0           56.15
10        13             1                0           49.95
11        16             1                2           18.95
12        58             1                1          100.35
13        49             1                1          103.70
14        25             1                1          105.50
15        69             1                1          113.25
16        52             1                2           20.65
17        71             1                1          106.70
18        10             1                0           55.20
19        21             1                1           90.05
20         1             0                0           39.65
21        12             1                2           19.80
22         1             1                2           20.15
23        58             1                0           59.90
24        49             1                0           59.60
25        30             1                0           55.30
26        47             1                1           99.35
27         1             0                0           30.20
28        72             1                0           90.25
29        17             1                0           64.70
...      ...           ...              ...             ...
7013      40             1                1           93.40
7014      41             1                1           89.20
7015      34             1                1           85.20
7016       1             1                0           49.95
7017      51             1                2           20.65
7018       1             1                1           70.65
7019      39             1                2           20.15
7020      12             1                2           19.20
7021      12             1                0           59.80
7022      72             1                1          104.95
7023      63             1                1          103.50
7024      44             1                1           84.80
7025      18             1                1           95.05
7026       9             1                0           44.20
7027      13             1                0           73.35
7028      68             1                0           64.10
7029       6             0                0           44.40
7030       2             1                2           20.05
7031      55             1                0           60.00
7032       1             1                1           75.75
7033      38             1                1           69.50
7034      67             1                1          102.95
7035      19             1                1           78.70
7036      12             0                0           60.65
7037      72             1                2           21.15
7038      24             1                0           84.80
7039      72             1                1          103.20
7040      11             0                0           29.60
7041       4             1                1           74.40
7042      66             1                1          105.65

[7043 rows x 4 columns]

In [25]:
y

0       0
1       0
2       1
3       0
4       1
5       1
6       0
7       0
8       1
9       0
10      0
11      0
12      0
13      1
14      0
15      0
16      0
17      0
18      1
19      0
20      1
21      0
22      1
23      0
24      0
25      0
26      1
27      1
28      0
29      1
       ..
7013    0
7014    0
7015    0
7016    0
7017    0
7018    1
7019    0
7020    0
7021    1
7022    0
7023    0
7024    0
7025    0
7026    1
7027    0
7028    0
7029    0
7030    0
7031    0
7032    1
7033    0
7034    1
7035    0
7036    0
7037    0
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int32

# Train:test=6:4

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=0)

In [28]:
X_train

tenure  PhoneService  InternetService  MonthlyCharges
6445       4             1                1           90.65
6218      70             0                0           58.40
471        1             1                0           55.00
4465      31             0                0           50.05
6047      13             1                0           65.85
3682       1             1                1           69.10
1349      51             0                0           49.65
3240      54             1                1          106.55
984       72             1                2           23.75
6505      56             1                0           59.80
1410       2             1                1           93.85
5738       1             1                2           20.60
5223      61             1                2           25.45
1276      71             1                1           99.40
6169       1             1                0           44.90
6565      61             1                1          106.20
2843      52             1                2           19.85
4138       1             1                1           85.45
2884      72             1                0           90.15
1309      18             1                1           85.20
775       72             1                1          110.65
4760      66             1                0           75.10
1480      39             0                0           35.55
4261      57             1                0           54.65
5300       1             1                1           80.05
1313      47             1                1          109.55
3241       1             1                2           20.10
4951      29             1                1           84.30
2204      67             1                1          111.30
3570      16             1                2           20.50
...      ...           ...              ...             ...
2046       1             0                0           24.70
4851       3             1                1           70.40
5072      23             1                1          104.45
2163      29             1                1           98.50
6036      53             1                1          110.50
6921      54             1                1           79.85
6216      58             1                0           71.60
2893      22             1                0           59.00
537       33             1                0           58.45
1701      66             1                1          102.45
2897      43             1                2           26.45
2222      38             1                1          101.15
2135      56             1                1          106.60
2599      72             1                0           73.00
705       25             1                1           79.85
6458       6             1                0           49.15
3468       1             1                2           19.70
6744      68             1                1          101.35
6743      10             1                2           24.00
5924      62             1                2           20.65
5874      10             1                1          100.60
4373      25             1                2           20.05
1033      62             1                2           23.65
5827      34             1                1           90.05
4859      63             1                1          108.50
4931      15             1                1          103.45
3264      10             1                1           91.10
1653      58             1                2           20.75
2607       1             1                1           69.75
2732       4             1                2           20.40

[4225 rows x 4 columns]

In [29]:
X_test

tenure  PhoneService  InternetService  MonthlyCharges
2200      19             1                0           58.20
4627      60             1                1          116.60
3225      13             1                0           71.95
2828       1             1                2           20.45
3768      55             1                1           77.75
4446       3             1                1           79.90
2234      23             1                0           59.70
5454       1             1                1           69.55
1278      36             0                0           60.70
578       35             1                1           94.55
5960      62             1                1           84.45
521       29             1                0           51.60
217       66             0                0           56.60
5716       2             1                0           55.30
202       71             1                1          105.55
134        2             1                0           44.35
154        6             1                2           19.70
4486      61             1                1           89.20
3283      69             1                2           20.35
3731       2             1                1           69.80
2572      71             1                2           25.00
4296      35             1                0           72.25
2838      41             1                2           20.00
3711      55             1                0           75.75
2425      26             1                2           20.30
5721      27             1                0           52.85
6429      67             1                0           69.35
5458       7             1                0           51.00
5549       3             1                1           97.90
6258       3             1                2           19.90
...      ...           ...              ...             ...
3391       4             1                2           19.00
913       12             1                2           20.05
720        2             1                2           20.20
122        3             1                1           74.40
3862      70             1                2           25.40
1853       1             1                0           45.15
6893       6             1                0           55.90
4717      38             1                1          110.70
4937      36             1                0           76.35
4522      30             1                2           20.70
5406      71             1                1           97.20
545       34             1                1           78.95
3131      72             1                0           78.45
6322       4             1                1           79.00
1673      41             1                1          113.60
6549       1             1                0           56.25
2311      48             1                1          104.50
4334      11             1                1           76.40
1047       3             1                0           50.25
1902      72             1                0           90.60
3515      17             1                0           55.50
4059       2             1                0           65.70
890       31             1                1           89.30
6861      14             1                1           91.65
1709      30             1                0           69.10
5508      70             1                2           25.15
118       41             1                2           20.65
4312      33             1                0           82.10
6532      18             1                2           20.35
1708       4             1                0           74.40

[2818 rows x 4 columns]

In [30]:
y_train

6445    0
6218    0
471     1
4465    0
6047    0
3682    1
1349    0
3240    1
984     0
6505    0
1410    1
5738    1
5223    0
1276    0
6169    1
6565    0
2843    0
4138    1
2884    0
1309    1
775     0
4760    0
1480    0
4261    0
5300    1
1313    1
3241    1
4951    0
2204    1
3570    0
       ..
2046    0
4851    1
5072    0
2163    1
6036    0
6921    0
6216    0
2893    1
537     0
1701    1
2897    0
2222    0
2135    0
2599    0
705     1
6458    0
3468    0
6744    0
6743    0
5924    0
5874    1
4373    0
1033    0
5827    0
4859    0
4931    0
3264    0
1653    0
2607    1
2732    0
Name: Churn, Length: 4225, dtype: int32

In [31]:
y_test

2200    0
4627    0
3225    0
2828    0
3768    0
4446    1
2234    0
5454    1
1278    0
578     0
5960    0
521     0
217     0
5716    0
202     0
134     1
154     0
4486    0
3283    0
3731    0
2572    0
4296    1
2838    0
3711    0
2425    0
5721    0
6429    0
5458    1
5549    1
6258    0
       ..
3391    0
913     0
720     0
122     1
3862    0
1853    1
6893    1
4717    0
4937    0
4522    0
5406    0
545     0
3131    0
6322    1
1673    1
6549    1
2311    0
4334    0
1047    0
1902    0
3515    0
4059    1
890     0
6861    1
1709    0
5508    0
118     0
4312    0
6532    0
1708    1
Name: Churn, Length: 2818, dtype: int32

# Logistic regression

In [33]:
from sklearn.linear_model.logistic import LogisticRegression
lr=LogisticRegression(random_state=0)
lr.fit(X_train,y_train)

C:\Users\Srinivasa Rao\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [34]:
y_pred=lr.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 1])

In [36]:
from sklearn.metrics import confusion_matrix
conf_matrix=confusion_matrix(y_pred,y_test)
conf_matrix

array([[1882,  408],
       [ 189,  339]], dtype=int64)

In [37]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)
acc

0.7881476224272533

# SVC

In [38]:
from sklearn.svm import SVC

In [39]:
sc=SVC(kernel='rbf')
sc_classifier=sc.fit(X_train,y_train)

C:\Users\Srinivasa Rao\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [41]:
svc_y_test=sc_classifier.predict(X_test)
svc_y_test

array([0, 0, 0, ..., 0, 0, 1])

In [44]:
from sklearn.metrics import confusion_matrix
svc_cm_test=confusion_matrix(y_test,svc_y_test)
svc_cm_test

array([[1871,  200],
       [ 428,  319]], dtype=int64)

In [45]:
svc_acc_test=accuracy_score(y_test,svc_y_test)
svc_acc_test

0.7771469127040455

# Decision Tree 

In [46]:
from sklearn.tree import DecisionTreeClassifier
dtc_clf=DecisionTreeClassifier()
dtc_clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [47]:
dtc_y_test=dtc_clf.predict(X_test)
dtc_y_test

array([0, 0, 0, ..., 0, 0, 1])

In [48]:
dtc_cm_test=confusion_matrix(y_test,dtc_y_test)
dtc_cm_test

array([[1700,  371],
       [ 414,  333]], dtype=int64)

In [49]:
dtc_acc_test=accuracy_score(y_test,dtc_y_test)
dtc_acc_test

0.7214336408800568

# Random Forest

In [50]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(max_depth=3,random_state=0)
rf_class=RandomForestClassifier()
rf_class.fit(X_train,y_train)

C:\Users\Srinivasa Rao\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [51]:
rf_class_y_test=dtc_clf.predict(X_test)
rf_class_y_test

array([0, 0, 0, ..., 0, 0, 1])

In [52]:
rf_cm_test=confusion_matrix(y_test,rf_class_y_test)
rf_cm_test

array([[1700,  371],
       [ 414,  333]], dtype=int64)

In [53]:
rf_acc_test=accuracy_score(y_test,rf_class_y_test)
rf_acc_test

0.7214336408800568

# Naive Bayes

In [54]:
from sklearn.naive_bayes import GaussianNB
clf=GaussianNB()
clf.fit(X_train,y_train)
GaussianNB()
y2_predict=clf.predict(X_test)

In [55]:
conf_matrix=confusion_matrix(y2_predict,y_test)
conf_matrix 

array([[1829,  386],
       [ 242,  361]], dtype=int64)

In [56]:
nvc=accuracy_score(y_test,y2_predict)
nvc

0.7771469127040455